name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
           python-version: 3.x
      - name: cml-run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
         # Your ML workflow goes here
         pip install --upgrade pip
         pip install -r requirements.txt
         python train.py
         
       
         echo "MODEL METRICS" 
         cat metrics.txt
      
     
