name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: dvcorg/cml-py3:latest
      options: --pull=always # This ensures the latest image is always pulled

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ML workflow
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          echo "Using the token: $CI_Token"
          python train.py

          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml-send-comment report.md
